In [1]:
import os
import sys
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# from utils.plot_function import *

work_path = "M:/1confiProj/"
os.chdir(work_path)
# Add parent directory to sys.path
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)
# from models.modelClassGPU import ConfiModel 
from utils.help_function import *

In [2]:
# load in data 
df_luis = pd.read_csv(os.path.join('P:\\3026008.02\\Luis', 'resultsCombinedExp.csv'))
df_luis.head()

,TrialNum,Report,Location,SecLocation,ReportedLocation,LocationCorrect,ReactionTime,Confidence,ConfidenceRT,CJ,...,CorrectCJ,CJRT,itiTime,BlockNum,Noise,Run,Task,Error,ReportedLocationMean,BehVar
0,1,2.0,-5.0,1.0,-5.0,1,0.624119,3,1.616947,2,...,1,3.403403,1.5,1,0,1,1,0.0,-3.979167,1.020833
1,2,2.0,-1.0,-1.0,-1.0,1,0.557044,2,0.777029,2,...,0,0.955938,1.5,1,0,1,1,0.0,-1.114583,0.114583
2,3,2.0,1.0,5.0,3.0,0,0.581250,4,0.902610,2,...,1,1.907387,1.5,1,0,1,1,2.0,1.093750,1.906250
3,4,2.0,-7.0,3.0,-7.0,1,0.344651,2,0.605402,2,...,1,0.509915,1.5,1,0,1,1,0.0,-5.802083,1.197917
4,5,2.0,7.0,3.0,7.0,1,0.603208,3,1.572621,2,...,1,2.224022,1.5,1,0,1,1,0.0,6.302083,0.697917

In [3]:
df_new = pd.DataFrame()
df_new.loc[df_luis.Report==1, 'AudLoc'] = df_luis.loc[df_luis.Report==1, 'Location']
df_new.loc[df_luis.Report==2, 'AudLoc'] = df_luis.loc[df_luis.Report==2, 'SecLocation']

df_new.loc[df_luis.Report==1, 'VisLoc'] = df_luis.loc[df_luis.Report==1, 'SecLocation']
df_new.loc[df_luis.Report==2, 'VisLoc'] = df_luis.loc[df_luis.Report==2, 'Location']

df_new['VisRel'] = 1
df_new['blockType'] = 2-df_luis.Report # 1 for auditory, 0 - for visual.

df_new['RespLoc'] = df_luis['ReportedLocation']
df_new['CICat'] = df_luis['Confidence']
df_new['Sources'] = df_luis['CJ']
df_new['ConfCat'] = df_luis['ConfidenceCJ']

df_new.head()

    AudLoc  VisLoc  VisRel  blockType  RespLoc  CICat  Sources  ConfCat
64    -1.0    -1.0       1        1.0     -3.0      3        2        1
65     5.0     5.0       1        1.0      7.0      3        2        3
66     5.0    -5.0       1        1.0      5.0      3        2        4
67    -7.0    -1.0       1        1.0     -3.0      3        2        2
68     5.0     1.0       1        1.0      3.0      3        2        1